### ISSUE TITLE
用快速排序算法进行接近有序数据的问题

### ISSUE THREAD

**Issue by Mickey-Wang** [liuyubobobo/Play-with-Algorithms#9]
用未做优化的快速排序对一百万的数据进行排序，随机性大的数据排序没有问题，但接近有序的数据排序会出现栈溢出的错误。同时，若把数据规模调成十万，就没有问题了。自己没有分析出问题所在，应该不是JVM内存或机子配置的问题，因为我同时用其他算法排序同等级别的数据时也不会报错。还请算法大神们帮忙看看，多谢~~

控制台信息如下：
```
Test for random array, size = 1000000 , random range [0, 1000000]
MergeSortOpt : 355ms
QuickSort : 242ms

Test for nearly ordered array, size = 1000000 , swap time = 100
MergeSortOpt : 121ms
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at generateTestCase.SortTestHelper.testSort(SortTestHelper.java:79)
	at test.testMain.main(testMain.java:72)
Caused by: java.lang.StackOverflowError
	at sortingAdvance.quickSort.QuickSort.partition(QuickSort.java:30)
	at sortingAdvance.quickSort.QuickSort.sort(QuickSort.java:41)
	at sortingAdvance.quickSort.QuickSort.sort(QuickSort.java:42)
	at sortingAdvance.quickSort.QuickSort.sort(QuickSort.java:42)
	at sortingAdvance.quickSort.QuickSort.sort(QuickSort.java:42)
	at sortingAdvance.quickSort.QuickSort.sort(QuickSort.java:42)
	at sortingAdvance.quickSort.QuickSort.sort(QuickSort.java:42)
	at sortingAdvance.quickSort.QuickSort.sort(QuickSort.java:42)
        ········
```

代码基本上是拷贝过来的，如下：
```java
private static int partition(Comparable[] arr, int l, int r){

        Comparable v = arr[l];

        // 注意初始条件
        int j = l; 
        // arr[l+1...j] < v ; arr[j+1...i) > v
        for( int i = l + 1 ; i <= r ; i ++ )
            if( arr[i].compareTo(v) < 0 ){
//                j ++;
//                swap(arr, j, i);
            		 swap(arr, ++j, i); // 更为优雅
            }

        swap(arr, l, j);

        return j;
    }

    // 递归使用快速排序,对arr[l...r]的范围进行排序
    private static void sort(Comparable[] arr, int l, int r){

        if( l >= r )
            return;

        int p = partition(arr, l, r);
        sort(arr, l, p-1 );
        sort(arr, p+1, r);
    }

    public static void sort(Comparable[] arr){

        int n = arr.length;
        sort(arr, 0, n-1);
    }

    private static void swap(Object[] arr, int i, int j) {
        Object t = arr[i];
        arr[i] = arr[j];
        arr[j] = t;
    }
```

**Comment by liuyubobobo** [comment]
因为没有使用随机化处理，使得每次partition的结果是极度偏离中心的。整个快速排序的递归深度和数据规模相当。数据规模大起来以后，递归深度过高，导致了栈溢出：）
